### ISSUE TITLE
Creación de usuarios

### ISSUE THREAD

**Issue by gallgarc** [plopezm/jee7-course#1]
¿Se debería controlar que no se pudiera crear más de un usuario con el mismo email y/o contraseña?

**Comment by gallgarc** [comment]
Vale, ya se controla en el capítulo 4 :)

**Comment by plopezm** [comment]
Hola gallarc,

Sí, lo he incluído más tarde, pero gracias por el apunte :) (conociéndome podría haberme olvidado)
